name: CI

# to run locally: act -P ubuntu-latest=shivammathur/setup-php@v2 -j shivammathur/node:latest -W ci.yml

on:
  push:
  pull_request:

jobs:
  code-style:
    uses: ./code-style.yml

  php-tests:
    needs: [code-style]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5', '8.4', '8.3', '8.2', '8.1']

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Run composer install
        run: composer install

      - name: Execute tests
        run: vendor/bin/phpunit
